server:
  port: 7777
spring:
  application:
    name: tx-demo2

  datasource:
      name: test
      url: jdbc:mysql://47.99.243.252:3306/demo2?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true
      username: root
      password: Aimai-910611
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
    mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.hehe.tx: debug

eureka:
  client:
    service-url:
         defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

# 分布式事物
tm:
  manager:
    url: http://localhost:8899/tx/manager/